// root
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const SET_MENU = 'SET_MENU';
export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_GLOBAL_CUSTOMER = 'SET_GLOBAL_CUSTOMER';

// product
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_PRODUCT_LIST_FOR_SELECT = 'SET_PRODUCT_LIST_FOR_SELECT';
export const SET_PRODUCT_CATEGORY = 'SET_PRODUCT_CATEGORY';
export const SET_PRODUCT_BRAND = 'SET_PRODUCT_BRAND';
export const SET_PRODUCT_UNITS = 'SET_PRODUCT_UNITS';
export const SET_ONLINE_CATE = 'SET_ONLINE_CATE';
export const SET_PRODUCT_HOT_SEARCH = 'SET_PRODUCT_HOT_SEARCH';

// supplier
export const SET_SUPPLIER_LIST = 'SET_SUPPLIER_LIST';

// customer
export const SET_CUSTOMER_LIST = 'SET_CUSTOMER_LIST';
export const SET_CUSTOMER_FOR_SEARCH_LIST = 'SET_CUSTOMER_FOR_SEARCH_LIST';
export const SET_CUSTOMER_FOR_SELECT_LIST = 'SET_CUSTOMER_FOR_SELECT_LIST';
export const SET_CUSTOMER_GRADE_LIST = 'SET_CUSTOMER_GRADE_LIST';
export const SET_CUSTOMER_NEWS_LETTER_LIST = 'SET_CUSTOMER_NEWS_LETTER_LIST';
export const SET_CUSTOMER_FEEDBACK_LIST = 'SET_CUSTOMER_FEEDBACK_LIST';

// system
export const SET_EMPLOYEE_LIST = 'SET_EMPLOYEE_LIST';
export const SET_BASIC_INFO = 'SET_BASIC_INFO';
export const SET_AREA_INFO = 'SET_AREA_INFO';
export const SET_ORDER_SEQUENCE = 'SET_ORDER_SEQUENCE';
export const CLEAR_BASIC_INFO = 'CLEAR_BASIC_INFO';
export const SET_COUNTRY_LIST = 'SET_COUNTRY_LIST';

// finance
export const SET_INVOICE_LIST = 'SET_INVOICE_LIST';
export const SET_PAYMENT_LIST = 'SET_PAYMENT_LIST';
export const SET_BANK_LIST = 'SET_BANK_LIST';
export const SET_PAYMENT_ORDER_LIST = 'SET_PAYMENT_ORDER_LIST';

// order
export const SET_ORDER_LIST = 'SET_ORDER_LIST';

// authority
export const SET_DEPARTMENT_LIST = 'SET_DEPARTMENT_LIST';
export const SET_AUTHORITY_LIST = 'SET_AUTHORITY_LIST';
export const SET_AUTHORITY_ROLE_LIST = 'SET_AUTHORITY_ROLE_LIST';

// warehouse
export const SET_WAREHOUSE_LIST = 'SET_WAREHOUSE_LIST';
export const SET_WAREHOUSE_INSTOCK_LIST = 'SET_WAREHOUSE_INSTOCK_LIST';
export const SET_WAREHOUSE_OUTSTOCK_LIST = 'SET_WAREHOUSE_OUTSTOCK_LIST';
export const SET_WAREHOUSE_INSTOCK_TYPE_LIST = 'SET_WAREHOUSE_INSTOCK_TYPE_LIST';
export const SET_WAREHOUSE_OUTSTOCK_TYPE_LIST = 'SET_WAREHOUSE_OUTSTOCK_TYPE_LIST';
export const SET_WAREHOUSE_PRODUCT_STOCK = 'SET_WAREHOUSE_PRODUCT_STOCK';
